sudo: true

services:
  - docker

before_install:
  - docker build -t petrepatrasc/docker-code .

script:
  - docker run -d --name code petrepatrasc/docker-code

after_script:
  - sudo docker kill $(docker ps -q);
  - sudo docker rm $(docker ps -aq);
  - sudo docker rmi $(docker images -q);
